name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  test_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Build prod bundle
        run: npm run build

      - name: Lint
        run: npm run lint
  test_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
